services:
  backend:
    build: .
    volumes:
      - ./:/app
    env_file:
      - .env
    environment:
      - DOMAIN=${DOMAIN}
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
    ports:
      - 8000:8000
volumes:
  app-db-data:
